name: "Game CI/CD"

env:
  GODOT_VERSION: 4.3
  ITCH_USERNAME: ${{ vars.ITCH_USERNAME }}
  ITCH_GAME: ${{ vars.ITCH_GAME }}
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

on:
  workflow_dispatch:
  push:
    branches:
      - refactor/add_env_to_ci

jobs:
  web:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Build
        run: godot -v --export-release --headless "Web"

      - name: Zip artifact
        run: zip -r web.zip .builds/web

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web_build
          path: web.zip

  release:    
    needs: [web]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Install butler
        run: |
          mkdir -p /opt/butler/bin
          cd /opt/butler/bin
          wget -O butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          export PATH=/opt/butler/bin/:$PATH
          butler -V

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: web_build

      - name: Upload artifact to itch.io
        run: |
          cd $GITHUB_WORKSPACE
          ls /opt/butler/bin
          /opt/butler/bin/butler push web.zip $ITCH_USERNAME/$ITCH_GAME:html