name: "Game CI/CD"

env:
  GODOT_VERSION: 4.3
  ITCH_USERNAME: ${{ vars.ITCH_USERNAME }}
  ITCH_GAME: ${{ vars.ITCH_GAME }}
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

on:
  workflow_dispatch:
  push:
    branches: [master, main, 'feat/ci_**',  'refactor/ci_**', 'fix/ci_**']

jobs:
  web:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Build
        run: godot -v --export-release --headless "Web"

      - name: Zip artifact
        run: |
          zip -r ${ITCH_GAME}_web.zip .builds/web

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.ITCH_GAME }}_web
          path: ${{ vars.ITCH_GAME }}_web.zip

  windows:
    runs-on: ubuntu-20.04    
    permissions:
      contents: write
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Check
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Build
        run: |
          godot -v --export-release --headless "Windows Desktop"
          mv .builds/win/game.exe .builds/win/${{ vars.ITCH_GAME }}.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.ITCH_GAME }}_win
          path: .builds/win/${{ vars.ITCH_GAME }}.exe

  linux:
    runs-on: ubuntu-20.04    
    permissions:
      contents: write
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Check
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Build
        run: |
          godot -v --export-release --headless "Linux/X11"
          mv .builds/linux/game.x86_64 .builds/linux/${{ vars.ITCH_GAME }}.x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.ITCH_GAME }}_linux_x86_64
          path: .builds/linux/${{ vars.ITCH_GAME }}.x86_64
        

  release:
    needs: [web, windows, linux]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Install butler
        run: |
          mkdir -p /opt/butler/bin
          cd /opt/butler/bin
          wget -O butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler

      - name: Download web artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ vars.ITCH_GAME }}_web

      - name: Upload web artifact to itch.io
        run: |
          cd $GITHUB_WORKSPACE
          /opt/butler/bin/butler push ${ITCH_GAME}_web.zip $ITCH_USERNAME/$ITCH_GAME:html

      - name: Download win artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ vars.ITCH_GAME }}_win
  
      - name: Upload win artifact to itch.io
        run: |
          cd $GITHUB_WORKSPACE
          ls
          /opt/butler/bin/butler push ${ITCH_GAME}.exe $ITCH_USERNAME/$ITCH_GAME:windows

      - name: Download linux artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ vars.ITCH_GAME }}_linux_x86_64
  
      - name: Upload linux artifact to itch.io
        run: |
          cd $GITHUB_WORKSPACE
          ls
          /opt/butler/bin/butler push ${ITCH_GAME}.x86_64 $ITCH_USERNAME/$ITCH_GAME:linux