name: "Game CI/CD"

env:
  GODOT_VERSION: 4.3

on:
  workflow_dispatch:
  push:
    branches:
      - feat/ci_cd # while the setup is going on

jobs:
  web:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Build
        run: godot -v --export-release --headless "Web"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-game
          path: .build/web